import { AppBar } from "@/components/Shared/AppBar/AppBar";
import "./globals.scss";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { RecoilWrapper } from "@/recoil/RecoilWrapper";
import { Drawer } from "@/components/Shared/Drawer/Drawer";
import { Footer } from "@/components/Shared/Footer/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <RecoilWrapper>
          <Drawer />
          <AppBar />
          {children}
          <Footer />
        </RecoilWrapper>
      </body>
    </html>
  );
}
